[package]
name = "user_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
buddy_system_allocator = "0.6"

[profile.release]
opt-level = "z" # Optimize for size.
strip = true    # Automatically strip symbols from the binary.
lto = true